source 'https://rubygems.org'
gem 'selenium-cucumber'
gem 'selenium-webdriver'
gem 'cucumber', '~>2.0.2'
gem 'minitest'
gem 'rails'
gem 'watir', '~>4.0'
gem 'watir-webdriver'
gem 'page-object'
gem 'pry'
gem 'spreadsheet'
# gem 'rubysl-win32ole'
# sudo apt-get install unixodbc-dev
gem 'roo'
gem 'roo-xls'
gem 'rake'
gem 'data_magic'
gem 'parallel_tests'
gem 'json'
gem "require_all"
# gem 'headless', :git => 'git://github.com/leonid-shevtsov/headless.git', :branch => 'wait-for-xvfb-to-launch'
# gem 'thor', '~>0.19.1'