source 'https://rubygems.org'
gem 'selenium-cucumber'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'rails'
gem 'watir', '~>4.0'
gem 'watir-webdriver'
gem 'page-object'
gem 'pry'
gem 'spreadsheet'
# gem 'rubysl-win32ole'
# sudo apt-get install unixodbc-dev
gem 'roo'
gem 'roo-xls'
gem 'rake'
gem 'data_magic'