source 'https://rubygems.org'
gem 'selenium-cucumber'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'rails'
gem 'watir', '~>4.0'
gem 'watir-webdriver'
gem 'page-object'
gem 'pry'
gem 'rubyXL'
gem 'spreadsheet'
gem 'importex'
gem 'rubysl-win32ole'
gem 'roo'
gem 'roo-xls'
gem 'ruby-odbc'
gem 'sequel'